//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.3ds.com/wserror", ClrNamespace="www._3ds.com.wserror")]



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="urn:com:dassault_systemes:webservice", ConfigurationName="IPLMKeyManagement")]
public interface IPLMKeyManagement
{
    
    // CODEGEN: Parameter 'oPLMKey' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(www._3ds.com.wserror.ErrorType), Action="", Name="generatePLMKeyFromSimpleContextErrorType")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="oPLMKey")]
    generatePLMKeyFromSimpleContextResponse generatePLMKeyFromSimpleContext(generatePLMKeyFromSimpleContextRequest request);
    
    // CODEGEN: Parameter 'oPLMKey' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(www._3ds.com.wserror.ErrorType), Action="", Name="generatePLMKeyFromStructuredContextErrorType")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(credential[]))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="oPLMKey")]
    generatePLMKeyFromStructuredContextResponse generatePLMKeyFromStructuredContext(generatePLMKeyFromStructuredContextRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(www._3ds.com.wserror.ErrorType), Action="", Name="revokePLMKeysErrorType")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(credential[]))]
    void revokePLMKeys(string iAdminKey, string iPLMKeys);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="generatePLMKeyFromSimpleContext", WrapperNamespace="urn:com:dassault_systemes:webservice", IsWrapped=true)]
public partial class generatePLMKeyFromSimpleContextRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com:dassault_systemes:webservice", Order=0)]
    public string iAdminKey;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com:dassault_systemes:webservice", Order=1)]
    public string iUserID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com:dassault_systemes:webservice", Order=2)]
    public string iUserPassword;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com:dassault_systemes:webservice", Order=3)]
    public string iContextURI;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com:dassault_systemes:webservice", Order=4)]
    public string iValidityURI;
    
    public generatePLMKeyFromSimpleContextRequest()
    {
    }
    
    public generatePLMKeyFromSimpleContextRequest(string iAdminKey, string iUserID, string iUserPassword, string iContextURI, string iValidityURI)
    {
        this.iAdminKey = iAdminKey;
        this.iUserID = iUserID;
        this.iUserPassword = iUserPassword;
        this.iContextURI = iContextURI;
        this.iValidityURI = iValidityURI;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="generatePLMKeyFromSimpleContextResponse", WrapperNamespace="urn:com:dassault_systemes:webservice", IsWrapped=true)]
public partial class generatePLMKeyFromSimpleContextResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com:dassault_systemes:webservice", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string oPLMKey;
    
    public generatePLMKeyFromSimpleContextResponse()
    {
    }
    
    public generatePLMKeyFromSimpleContextResponse(string oPLMKey)
    {
        this.oPLMKey = oPLMKey;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:com:dassault_systemes:webservice:infra:keymgt")]
public partial class CredentialSet
{
    
    private credential[] authenticationField;
    
    private credential[] applicativeField;
    
    private credential[] validityField;
    
    private string idField;
    
    private string versionField;
    
    public CredentialSet()
    {
        this.versionField = "1.0";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("credential", IsNullable=false)]
    public credential[] authentication
    {
        get
        {
            return this.authenticationField;
        }
        set
        {
            this.authenticationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
    [System.Xml.Serialization.XmlArrayItemAttribute("credential", IsNullable=false)]
    public credential[] applicative
    {
        get
        {
            return this.applicativeField;
        }
        set
        {
            this.applicativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
    [System.Xml.Serialization.XmlArrayItemAttribute("credential", IsNullable=false)]
    public credential[] validity
    {
        get
        {
            return this.validityField;
        }
        set
        {
            this.validityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("1.0")]
    public string version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.30")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class credential
{
    
    private string nameField;
    
    private bool ispasswordField;
    
    private string valueField;
    
    public credential()
    {
        this.ispasswordField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool ispassword
    {
        get
        {
            return this.ispasswordField;
        }
        set
        {
            this.ispasswordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="generatePLMKeyFromStructuredContext", WrapperNamespace="urn:com:dassault_systemes:webservice", IsWrapped=true)]
public partial class generatePLMKeyFromStructuredContextRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com:dassault_systemes:webservice", Order=0)]
    public string iAdminKey;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com:dassault_systemes:webservice", Order=1)]
    public CredentialSet iCredentialSet;
    
    public generatePLMKeyFromStructuredContextRequest()
    {
    }
    
    public generatePLMKeyFromStructuredContextRequest(string iAdminKey, CredentialSet iCredentialSet)
    {
        this.iAdminKey = iAdminKey;
        this.iCredentialSet = iCredentialSet;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="generatePLMKeyFromStructuredContextResponse", WrapperNamespace="urn:com:dassault_systemes:webservice", IsWrapped=true)]
public partial class generatePLMKeyFromStructuredContextResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:com:dassault_systemes:webservice", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string oPLMKey;
    
    public generatePLMKeyFromStructuredContextResponse()
    {
    }
    
    public generatePLMKeyFromStructuredContextResponse(string oPLMKey)
    {
        this.oPLMKey = oPLMKey;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IPLMKeyManagementChannel : IPLMKeyManagement, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class PLMKeyManagementClient : System.ServiceModel.ClientBase<IPLMKeyManagement>, IPLMKeyManagement
{
    
    public PLMKeyManagementClient()
    {
    }
    
    public PLMKeyManagementClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public PLMKeyManagementClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PLMKeyManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PLMKeyManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    generatePLMKeyFromSimpleContextResponse IPLMKeyManagement.generatePLMKeyFromSimpleContext(generatePLMKeyFromSimpleContextRequest request)
    {
        return base.Channel.generatePLMKeyFromSimpleContext(request);
    }
    
    public string generatePLMKeyFromSimpleContext(string iAdminKey, string iUserID, string iUserPassword, string iContextURI, string iValidityURI)
    {
        generatePLMKeyFromSimpleContextRequest inValue = new generatePLMKeyFromSimpleContextRequest();
        inValue.iAdminKey = iAdminKey;
        inValue.iUserID = iUserID;
        inValue.iUserPassword = iUserPassword;
        inValue.iContextURI = iContextURI;
        inValue.iValidityURI = iValidityURI;
        generatePLMKeyFromSimpleContextResponse retVal = ((IPLMKeyManagement)(this)).generatePLMKeyFromSimpleContext(inValue);
        return retVal.oPLMKey;
    }
    
    generatePLMKeyFromStructuredContextResponse IPLMKeyManagement.generatePLMKeyFromStructuredContext(generatePLMKeyFromStructuredContextRequest request)
    {
        return base.Channel.generatePLMKeyFromStructuredContext(request);
    }
    
    public string generatePLMKeyFromStructuredContext(string iAdminKey, CredentialSet iCredentialSet)
    {
        generatePLMKeyFromStructuredContextRequest inValue = new generatePLMKeyFromStructuredContextRequest();
        inValue.iAdminKey = iAdminKey;
        inValue.iCredentialSet = iCredentialSet;
        generatePLMKeyFromStructuredContextResponse retVal = ((IPLMKeyManagement)(this)).generatePLMKeyFromStructuredContext(inValue);
        return retVal.oPLMKey;
    }
    
    public void revokePLMKeys(string iAdminKey, string iPLMKeys)
    {
        base.Channel.revokePLMKeys(iAdminKey, iPLMKeys);
    }
}
namespace www._3ds.com.wserror
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ErrorType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        private string messageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
}
