
package com.dassault_systemes.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * Interface to test the responsiveness of the application server.
 * 
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IPingService", targetNamespace = "urn:com:dassault_systemes:webservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IPingService {


    /**
     * Pings the application server by sending it a simple message
     * 
     * @param parameters
     * @return
     *     returns com.dassault_systemes.webservice.PingResponse
     * @throws PingErrorType
     */
    @WebMethod
    @WebResult(name = "pingResponse", targetNamespace = "urn:com:dassault_systemes:webservice", partName = "parameters")
    public PingResponse ping(
        @WebParam(name = "ping", targetNamespace = "urn:com:dassault_systemes:webservice", partName = "parameters")
        Ping parameters)
        throws PingErrorType
    ;

}
