
package com.dassault_systemes.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "PingService", targetNamespace = "urn:com:dassault_systemes:webservice", wsdlLocation = "http://pelfortdsy:8090/ematrix/webservice?command=get&id=ping&type=wsdl")
public class PingService
    extends Service
{

    private final static URL PINGSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://pelfortdsy:8090/ematrix/webservice?command=get&id=ping&type=wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        PINGSERVICE_WSDL_LOCATION = url;
    }

    public PingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PingService() {
        super(PINGSERVICE_WSDL_LOCATION, new QName("urn:com:dassault_systemes:webservice", "PingService"));
    }

    /**
     * 
     * @return
     *     returns IPingService
     */
    @WebEndpoint(name = "PingServicePort")
    public IPingService getPingServicePort() {
        return (IPingService)super.getPort(new QName("urn:com:dassault_systemes:webservice", "PingServicePort"), IPingService.class);
    }

}
