
package com.dassault_systemes.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * Interface to test the responsiveness of the application server.
 * 
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IPingService", targetNamespace = "urn:com:dassault_systemes:webservice")
public interface IPingService {


    /**
     * Pings the application server by sending it a simple message
     * 
     * @param iSentence
     * @return
     *     returns java.lang.Integer
     * @throws PingErrorType
     */
    @WebMethod
    @WebResult(name = "oWordCount", targetNamespace = "urn:com:dassault_systemes:webservice")
    @RequestWrapper(localName = "ping", targetNamespace = "urn:com:dassault_systemes:webservice", className = "com.dassault_systemes.webservice.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "urn:com:dassault_systemes:webservice", className = "com.dassault_systemes.webservice.PingResponse")
    public Integer ping(
        @WebParam(name = "iSentence", targetNamespace = "urn:com:dassault_systemes:webservice")
        String iSentence)
        throws PingErrorType
    ;

}
