
package com.dassault_systemes.webservice;

import javax.xml.ws.WebFault;
import com._3ds.wserror.ErrorType;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "pingErrorType", targetNamespace = "urn:com:dassault_systemes:webservice")
public class PingErrorType
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ErrorType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public PingErrorType(String message, ErrorType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public PingErrorType(String message, ErrorType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com._3ds.wserror.ErrorType
     */
    public ErrorType getFaultInfo() {
        return faultInfo;
    }

}
