//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.3ds.com/wserror", ClrNamespace="www._3ds.com.wserror")]

namespace www._3ds.com.wserror
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ErrorType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        private string messageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="urn:com:dassault_systemes:webservice", ConfigurationName="IPingService")]
public interface IPingService
{
    
    // CODEGEN: Generating message contract since element name iSentence from namespace urn:com:dassault_systemes:webservice is not marked nillable
    [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="ping", ReplyAction="pingResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(www._3ds.com.wserror.ErrorType), Action="ErrorType", ProtectionLevel=System.Net.Security.ProtectionLevel.None, Name="pingErrorType")]
    pingResponse ping(pingRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class pingRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="ping", Namespace="urn:com:dassault_systemes:webservice", Order=0)]
    public pingRequestBody Body;
    
    public pingRequest()
    {
    }
    
    public pingRequest(pingRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="urn:com:dassault_systemes:webservice")]
public partial class pingRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string iSentence;
    
    public pingRequestBody()
    {
    }
    
    public pingRequestBody(string iSentence)
    {
        this.iSentence = iSentence;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class pingResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="pingResponse", Namespace="urn:com:dassault_systemes:webservice", Order=0)]
    public pingResponseBody Body;
    
    public pingResponse()
    {
    }
    
    public pingResponse(pingResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace="urn:com:dassault_systemes:webservice")]
public partial class pingResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public System.Nullable<int> oWordCount;
    
    public pingResponseBody()
    {
    }
    
    public pingResponseBody(System.Nullable<int> oWordCount)
    {
        this.oWordCount = oWordCount;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IPingServiceChannel : IPingService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class PingServiceClient : System.ServiceModel.ClientBase<IPingService>, IPingService
{
    
    public PingServiceClient()
    {
    }
    
    public PingServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public PingServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    pingResponse IPingService.ping(pingRequest request)
    {
        return base.Channel.ping(request);
    }
    
    public System.Nullable<int> ping(string iSentence)
    {
        pingRequest inValue = new pingRequest();
        inValue.Body = new pingRequestBody();
        inValue.Body.iSentence = iSentence;
        pingResponse retVal = ((IPingService)(this)).ping(inValue);
        return retVal.Body.oWordCount;
    }
}
